version: '3.1'

services:

  db:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-rootpassword}
      MYSQL_DATABASE: ${MYSQL_DATABASE:-exampledb}
      MYSQL_USER: ${MYSQL_USER:-exampleuser}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD:-examplepassword}
      MYSQL_ALLOW_EMPTY_PASSWORD: 'no'
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - "3306:3306"
    expose:
      - "3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
